name = "SymbolicPlanners"
uuid = "b6fe5377-9711-4fad-95b0-be4eed71ecbb"
authors = ["Xuan <tanqazx@gmail.com>"]
version = "0.1.22"

[deps]
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
PDDL = "2c8894f9-daa1-498a-9e3a-26edd9623db8"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
AutoHashEquals = "0.2, 1.0, 2"
DataStructures = "0.18"
DocStringExtensions = "0.8, 0.9"
Logging = "<0.0.1, 1"
PDDL = "0.2.17"
Parameters = "0.12"
PlanningDomains = "0.1.3"
Random = "<0.0.1, 1"
StatsBase = "0.33, 0.34"
julia = "1.3"

[extras]
PlanningDomains = "34fa33c8-33e3-4e77-bac8-de592315aba2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "PlanningDomains"]
